/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminModule: typeof import('./src/components/AdminModule.vue')['default']
    AdminNavbar: typeof import('./src/components/AdminNavbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Menu: typeof import('primevue/menu')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserIcon: typeof import('./src/components/UserIcon.vue')['default']
  }
}
